apiVersion: v2
name: gha-stateful-runner
description: A Helm chart for deploying GitHub Actions self-hosted runners using ui token without PAT.
type: application
version: 1.1.0
appVersion: "1.1.0"
icon: https://avatars.githubusercontent.com/u/9919
home: https://github.com/eric2788/k8s-gha-stateful-runner
sources:
  - https://github.com/eric2788/k8s-gha-stateful-runner
keywords:
  - github-actions
  - runner
  - ci-cd
  - self-hosted
  - kubernetes
maintainers:
  - name: eric2788
    url: https://github.com/eric2788
