{{- if $.Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "actions-runner.fullname" $ }}-pdb
  {{- include "actions-runner.optionalNamespace" $ }}
  labels:
    {{- include "actions-runner.labels" $ | nindent 4 }}
spec:
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "actions-runner.selectorLabels" $ | nindent 6 }}
{{- end }}
