{{- if not .Values.runner.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "actions-runner.fullname" $ }}-secret
data:
  ui_token: {{ $.Values.runner.token | trim | b64enc | quote }}
{{- end }}